export const countries = [
    { name: 'Afghanistan', country: 'af', flag: '🇦🇫' },
    { name: 'Albania', country: 'al', flag: '🇦🇱' },
    { name: 'Algeria', country: 'dz', flag: '🇩🇿' },
    { name: 'Andorra', country: 'ad', flag: '🇦🇩' },
    { name: 'Angola', country: 'ao', flag: '🇦🇴' },
    { name: 'Antigua and Barbuda', country: 'ag', flag: '🇦🇬' },
    { name: 'Argentina', country: 'ar', flag: '🇦🇷' },
    { name: 'Armenia', country: 'am', flag: '🇦🇲' },
    { name: 'Australia', country: 'au', flag: '🇦🇺' },
    { name: 'Austria', country: 'at', flag: '🇦🇹' },
    { name: 'Azerbaijan', country: 'az', flag: '🇦🇿' },
    { name: 'Bahamas', country: 'bs', flag: '🇧🇸' },
    { name: 'Bahrain', country: 'bh', flag: '🇧🇭' },
    { name: 'Bangladesh', country: 'bd', flag: '🇧🇩' },
    { name: 'Barbados', country: 'bb', flag: '🇧🇧' },
    { name: 'Belarus', country: 'by', flag: '🇧🇾' },
    { name: 'Belgium', country: 'be', flag: '🇧🇪' },
    { name: 'Belize', country: 'bz', flag: '🇧🇿' },
    { name: 'Benin', country: 'bj', flag: '🇧🇯' },
    { name: 'Bhutan', country: 'bt', flag: '🇧🇹' },
    { name: 'Bolivia', country: 'bo', flag: '🇧🇴' },
    { name: 'Bosnia and Herzegovina', country: 'ba', flag: '🇧🇦' },
    { name: 'Botswana', country: 'bw', flag: '🇧🇼' },
    { name: 'Brazil', country: 'br', flag: '🇧🇷' },
    { name: 'Brunei', country: 'bn', flag: '🇧🇳' },
    { name: 'Bulgaria', country: 'bg', flag: '🇧🇬' },
    { name: 'Burkina Faso', country: 'bf', flag: '🇧🇫' },
    { name: 'Burundi', country: 'bi', flag: '🇧🇮' },
    { name: 'Cabo Verde', country: 'cv', flag: '🇨🇻' },
    { name: 'Cambodia', country: 'kh', flag: '🇰🇭' },
    { name: 'Cameroon', country: 'cm', flag: '🇨🇲' },
    { name: 'Canada', country: 'ca', flag: '🇨🇦' },
    { name: 'Central African Republic', country: 'cf', flag: '🇨🇫' },
    { name: 'Chad', country: 'td', flag: '🇹🇩' },
    { name: 'Chile', country: 'cl', flag: '🇨🇱' },
    { name: 'China', country: 'cn', flag: '🇨🇳' },
    { name: 'Colombia', country: 'co', flag: '🇨🇴' },
    { name: 'Comoros', country: 'km', flag: '🇰🇲' },
    { name: 'Congo, Democratic Republic of the', country: 'cd', flag: '🇨🇩' },
    { name: 'Congo, Republic of the', country: 'cg', flag: '🇨🇬' },
    { name: 'Costa Rica', country: 'cr', flag: '🇨🇷' },
    { name: 'Croatia', country: 'hr', flag: '🇭🇷' },
    { name: 'Cuba', country: 'cu', flag: '🇨🇺' },
    { name: 'Cyprus', country: 'cy', flag: '🇨🇾' },
    { name: 'Czech Republic', country: 'cz', flag: '🇨🇿' },
    { name: 'Denmark', country: 'dk', flag: '🇩🇰' },
    { name: 'Djibouti', country: 'dj', flag: '🇩🇯' },
    { name: 'Dominica', country: 'dm', flag: '🇩🇲' },
    { name: 'Dominican Republic', country: 'do', flag: '🇩🇴' },
    { name: 'Ecuador', country: 'ec', flag: '🇪🇨' },
    { name: 'Egypt', country: 'eg', flag: '🇪🇬' },
    { name: 'El Salvador', country: 'sv', flag: '🇸🇻' },
    { name: 'Equatorial Guinea', country: 'gq', flag: '🇬🇶' },
    { name: 'Eritrea', country: 'er', flag: '🇪🇷' },
    { name: 'Estonia', country: 'ee', flag: '🇪🇪' },
    { name: 'Eswatini', country: 'sz', flag: '🇸🇿' },
    { name: 'Ethiopia', country: 'et', flag: '🇪🇹' },
    { name: 'Fiji', country: 'fj', flag: '🇫🇯' },
    { name: 'Finland', country: 'fi', flag: '🇫🇮' },
    { name: 'France', country: 'fr', flag: '🇫🇷' },
    { name: 'Gabon', country: 'ga', flag: '🇬🇦' },
    { name: 'Gambia', country: 'gm', flag: '🇬🇲' },
    { name: 'Georgia', country: 'ge', flag: '🇬🇪' },
    { name: 'Germany', country: 'de', flag: '🇩🇪' },
    { name: 'Ghana', country: 'gh', flag: '🇬🇭' },
    { name: 'Greece', country: 'gr', flag: '🇬🇷' },
    { name: 'Grenada', country: 'gd', flag: '🇬🇩' },
    { name: 'Guatemala', country: 'gt', flag: '🇬🇹' },
    { name: 'Guinea', country: 'gn', flag: '🇬🇳' },
    { name: 'Guinea-Bissau', country: 'gw', flag: '🇬🇼' },
    { name: 'Guyana', country: 'gy', flag: '🇬🇾' },
    { name: 'Haiti', country: 'ht', flag: '🇭🇹' },
    { name: 'Honduras', country: 'hn', flag: '🇭🇳' },
    { name: 'Hungary', country: 'hu', flag: '🇭🇺' },
    { name: 'Iceland', country: 'is', flag: '🇮🇸' },
    { name: 'India', country: 'in', flag: '🇮🇳' },
    { name: 'Indonesia', country: 'id', flag: '🇮🇩' },
    { name: 'Iran', country: 'ir', flag: '🇮🇷' },
    { name: 'Iraq', country: 'iq', flag: '🇮🇶' },
    { name: 'Ireland', country: 'ie', flag: '🇮🇪' },
    { name: 'Israel', country: 'il', flag: '🇮🇱' },
    { name: 'Italy', country: 'it', flag: '🇮🇹' },
    { name: 'Jamaica', country: 'jm', flag: '🇯🇲' },
    { name: 'Japan', country: 'jp', flag: '🇯🇵' },
    { name: 'Jordan', country: 'jo', flag: '🇯🇴' },
    { name: 'Kazakhstan', country: 'kz', flag: '🇰🇿' },
    { name: 'Kenya', country: 'ke', flag: '🇰🇪' },
    { name: 'Kiribati', country: 'ki', flag: '🇰🇮' },
    { name: 'Korea, North', country: 'kp', flag: '🇰🇵' },
    { name: 'Korea, South', country: 'kr', flag: '🇰🇷' },
    { name: 'Kuwait', country: 'kw', flag: '🇰🇼' },
    { name: 'Kyrgyzstan', country: 'kg', flag: '🇰🇬' },
    { name: 'Laos', country: 'la', flag: '🇱🇦' },
    { name: 'Latvia', country: 'lv', flag: '🇱🇻' },
    { name: 'Lebanon', country: 'lb', flag: '🇱🇧' },
    { name: 'Lesotho', country: 'ls', flag: '🇱🇸' },
    { name: 'Liberia', country: 'lr', flag: '🇱🇷' },
    { name: 'Libya', country: 'ly', flag: '🇱🇾' },
    { name: 'Liechtenstein', country: 'li', flag: '🇱🇮' },
    { name: 'Lithuania', country: 'lt', flag: '🇱🇹' },
    { name: 'Luxembourg', country: 'lu', flag: '🇱🇺' },
    { name: 'Madagascar', country: 'mg', flag: '🇲🇬' },
    { name: 'Malawi', country: 'mw', flag: '🇲🇼' },
    { name: 'Malaysia', country: 'my', flag: '🇲🇾' },
    { name: 'Maldives', country: 'mv', flag: '🇲🇻' },
    { name: 'Mali', country: 'ml', flag: '🇲🇱' },
    { name: 'Malta', country: 'mt', flag: '🇲🇹' },
    { name: 'Marshall Islands', country: 'mh', flag: '🇲🇭' },
    { name: 'Mauritania', country: 'mr', flag: '🇲🇷' },
    { name: 'Mauritius', country: 'mu', flag: '🇲🇺' },
    { name: 'Mexico', country: 'mx', flag: '🇲🇽' },
    { name: 'Micronesia', country: 'fm', flag: '🇫🇲' },
    { name: 'Moldova', country: 'md', flag: '🇲🇩' },
    { name: 'Monaco', country: 'mc', flag: '🇲🇨' },
    { name: 'Mongolia', country: 'mn', flag: '🇲🇳' },
    { name: 'Montenegro', country: 'me', flag: '🇲🇪' },
    { name: 'Morocco', country: 'ma', flag: '🇲🇦' },
    { name: 'Mozambique', country: 'mz', flag: '🇲🇿' },
    { name: 'Myanmar', country: 'mm', flag: '🇲🇲' },
    { name: 'Namibia', country: 'na', flag: '🇳🇦' },
    { name: 'Nauru', country: 'nr', flag: '🇳🇷' },
    { name: 'Nepal', country: 'np', flag: '🇳🇵' },
    { name: 'Netherlands', country: 'nl', flag: '🇳🇱' },
    { name: 'New Zealand', country: 'nz', flag: '🇳🇿' },
    { name: 'Nicaragua', country: 'ni', flag: '🇳🇮' },
    { name: 'Niger', country: 'ne', flag: '🇳🇪' },
    { name: 'Nigeria', country: 'ng', flag: '🇳🇬' },
    { name: 'North Macedonia', country: 'mk', flag: '🇲🇰' },
    { name: 'Norway', country: 'no', flag: '🇳🇴' },
    { name: 'Oman', country: 'om', flag: '🇴🇲' },
    { name: 'Pakistan', country: 'pk', flag: '🇵🇰' },
    { name: 'Palau', country: 'pw', flag: '🇵🇼' },
    { name: 'Palestine', country: 'ps', flag: '🇵🇸' },
    { name: 'Panama', country: 'pa', flag: '🇵🇦' },
    { name: 'Papua New Guinea', country: 'pg', flag: '🇵🇬' },
    { name: 'Paraguay', country: 'py', flag: '🇵🇾' },
    { name: 'Peru', country: 'pe', flag: '🇵🇪' },
    { name: 'Philippines', country: 'ph', flag: '🇵🇭' },
    { name: 'Poland', country: 'pl', flag: '🇵🇱' },
    { name: 'Portugal', country: 'pt', flag: '🇵🇹' },
    { name: 'Qatar', country: 'qa', flag: '🇶🇦' },
    { name: 'Romania', country: 'ro', flag: '🇷🇴' },
    { name: 'Russia', country: 'ru', flag: '🇷🇺' },
    { name: 'Rwanda', country: 'rw', flag: '🇷🇼' },
    { name: 'Saint Kitts and Nevis', country: 'kn', flag: '🇰🇳' },
    { name: 'Saint Lucia', country: 'lc', flag: '🇱🇨' },
    { name: 'Saint Vincent and the Grenadines', country: 'vc', flag: '🇻🇨' },
    { name: 'Samoa', country: 'ws', flag: '🇼🇸' },
    { name: 'San Marino', country: 'sm', flag: '🇸🇲' },
    { name: 'Sao Tome and Principe', country: 'st', flag: '🇸🇹' },
    { name: 'Saudi Arabia', country: 'sa', flag: '🇸🇦' },
    { name: 'Senegal', country: 'sn', flag: '🇸🇳' },
    { name: 'Serbia', country: 'rs', flag: '🇷🇸' },
    { name: 'Seychelles', country: 'sc', flag: '🇸🇨' },
    { name: 'Sierra Leone', country: 'sl', flag: '🇸🇱' },
    { name: 'Singapore', country: 'sg', flag: '🇸🇬' },
    { name: 'Slovakia', country: 'sk', flag: '🇸🇰' },
    { name: 'Slovenia', country: 'si', flag: '🇸🇮' },
    { name: 'Solomon Islands', country: 'sb', flag: '🇸🇧' },
    { name: 'Somalia', country: 'so', flag: '🇸🇴' },
    { name: 'South Africa', country: 'za', flag: '🇿🇦' },
    { name: 'South Sudan', country: 'ss', flag: '🇸🇸' },
    { name: 'Spain', country: 'es', flag: '🇪🇸' },
    { name: 'Sri Lanka', country: 'lk', flag: '🇱🇰' },
    { name: 'Sudan', country: 'sd', flag: '🇸🇩' },
    { name: 'Suriname', country: 'sr', flag: '🇸🇷' },
    { name: 'Sweden', country: 'se', flag: '🇸🇪' },
    { name: 'Switzerland', country: 'ch', flag: '🇨🇭' },
    { name: 'Syria', country: 'sy', flag: '🇸🇾' },
    { name: 'Taiwan', country: 'tw', flag: '🇹🇼' },
    { name: 'Tajikistan', country: 'tj', flag: '🇹🇯' },
    { name: 'Tanzania', country: 'tz', flag: '🇹🇿' },
    { name: 'Thailand', country: 'th', flag: '🇹🇭' },
    { name: 'Timor-Leste', country: 'tl', flag: '🇹🇱' },
    { name: 'Togo', country: 'tg', flag: '🇹🇬' },
    { name: 'Tonga', country: 'to', flag: '🇹🇴' },
    { name: 'Trinidad and Tobago', country: 'tt', flag: '🇹🇹' },
    { name: 'Tunisia', country: 'tn', flag: '🇹🇳' },
    { name: 'Turkey', country: 'tr', flag: '🇹🇷' },
    { name: 'Turkmenistan', country: 'tm', flag: '🇹🇲' },
    { name: 'Tuvalu', country: 'tv', flag: '🇹🇻' },
    { name: 'Uganda', country: 'ug', flag: '🇺🇬' },
    { name: 'Ukraine', country: 'ua', flag: '🇺🇦' },
    { name: 'United Arab Emirates', country: 'ae', flag: '🇦🇪' },
    { name: 'United Kingdom', country: 'gb', flag: '🇬🇧' },
    { name: 'United States', country: 'us', flag: '🇺🇸' },
    { name: 'Uruguay', country: 'uy', flag: '🇺🇾' },
    { name: 'Uzbekistan', country: 'uz', flag: '🇺🇿' },
    { name: 'Vanuatu', country: 'vu', flag: '🇻🇺' },
    { name: 'Vatican City', country: 'va', flag: '🇻🇦' },
    { name: 'Venezuela', country: 've', flag: '🇻🇪' },
    { name: 'Vietnam', country: 'vn', flag: '🇻🇳' },
    { name: 'Yemen', country: 'ye', flag: '🇾🇪' },
    { name: 'Zambia', country: 'zm', flag: '🇿🇲' },
    { name: 'Zimbabwe', country: 'zw', flag: '🇿🇼' },
];

