export const currencies = [
    { name: "Afghanistan", country: "AF", currency: "Afghani", symbol: "؋", code: "AFN" },
    { name: "Albania", country: "AL", currency: "Albanian Lek", symbol: "Lek", code: "ALL" },
    { name: "Algeria", country: "DZ", currency: "Algerian Dinar", symbol: "د.ج", code: "DZD" },
    { name: "Andorra", country: "AD", currency: "Euro", symbol: "€", code: "EUR" },
    { name: "Angola", country: "AO", currency: "Angolan Kwanza", symbol: "Kz", code: "AOA" },
    { name: "Antigua and Barbuda", country: "AG", currency: "East Caribbean Dollar", symbol: "EC$", code: "XCD" },
    { name: "Argentina", country: "AR", currency: "Argentine Peso", symbol: "$", code: "ARS" },
    { name: "Armenia", country: "AM", currency: "Armenian Dram", symbol: "֏", code: "AMD" },
    { name: "Australia", country: "AU", currency: "Australian Dollar", symbol: "A$", code: "AUD" },
    { name: "Austria", country: "AT", currency: "Euro", symbol: "€", code: "EUR" },
    { name: "Azerbaijan", country: "AZ", currency: "Azerbaijan Manat", symbol: "₼", code: "AZN" },
    { name: "Bahamas", country: "BS", currency: "Bahamian Dollar", symbol: "B$", code: "BSD" },
    { name: "Bahrain", country: "BH", currency: "Bahraini Dinar", symbol: "BD", code: "BHD" },
    { name: "Bangladesh", country: "BD", currency: "Bangladeshi Taka", symbol: "৳", code: "BDT" },
    { name: "Barbados", country: "BB", currency: "Barbadian Dollar", symbol: "Bds$", code: "BBD" },
    { name: "Belarus", country: "BY", currency: "Belarusian Ruble", symbol: "Br", code: "BYN" },
    { name: "Belgium", country: "BE", currency: "Euro", symbol: "€", code: "EUR" },
    { name: "Belize", country: "BZ", currency: "Belize Dollar", symbol: "BZ$", code: "BZD" },
    { name: "Benin", country: "BJ", currency: "West African CFA Franc", symbol: "CFA", code: "XOF" },
    { name: "Bhutan", country: "BT", currency: "Bhutanese Ngultrum", symbol: "Nu.", code: "BTN" },
    { name: "Bolivia", country: "BO", currency: "Bolivian Boliviano", symbol: "Bs.", code: "BOB" },
    { name: "Bosnia and Herzegovina", country: "BA", currency: "Convertible Mark", symbol: "KM", code: "BAM" },
    { name: "Botswana", country: "BW", currency: "Botswana Pula", symbol: "P", code: "BWP" },
    { name: "Brazil", country: "BR", currency: "Brazilian Real", symbol: "R$", code: "BRL" },
    { name: "Brunei", country: "BN", currency: "Brunei Dollar", symbol: "B$", code: "BND" },
    { name: "Bulgaria", country: "BG", currency: "Bulgarian Lev", symbol: "лв", code: "BGN" },
    { name: "Burkina Faso", country: "BF", currency: "West African CFA Franc", symbol: "CFA", code: "XOF" },
    { name: "Burundi", country: "BI", currency: "Burundian Franc", symbol: "FBu", code: "BIF" },
    { name: "Cabo Verde", country: "CV", currency: "Cape Verdean Escudo", symbol: "CVE", code: "CVE" },
    { name: "Cambodia", country: "KH", currency: "Cambodian Riel", symbol: "៛", code: "KHR" },
    { name: "Cameroon", country: "CM", currency: "Central African CFA Franc", symbol: "FCFA", code: "XAF" },
    { name: "Canada", country: "CA", currency: "Canadian Dollar", symbol: "CA$", code: "CAD" },
    { name: "Central African Republic", country: "CF", currency: "Central African CFA Franc", symbol: "FCFA", code: "XAF" },
    { name: "Chad", country: "TD", currency: "Central African CFA Franc", symbol: "FCFA", code: "XAF" },
    { name: "Chile", country: "CL", currency: "Chilean Peso", symbol: "$", code: "CLP" },
    { name: "China", country: "CN", currency: "Chinese Yuan Renminbi", symbol: "¥", code: "CNY" },
    { name: "Colombia", country: "CO", currency: "Colombian Peso", symbol: "$", code: "COP" },
    { name: "Comoros", country: "KM", currency: "Comorian Franc", symbol: "CF", code: "KMF" },
    { name: "Congo (Brazzaville)", country: "CG", currency: "Central African CFA Franc", symbol: "FCFA", code: "XAF" },
    { name: "Congo (Kinshasa)", country: "CD", currency: "Congolese Franc", symbol: "FC", code: "CDF" },
    { name: "Costa Rica", country: "CR", currency: "Costa Rican Colon", symbol: "₡", code: "CRC" },
    { name: "Croatia", country: "HR", currency: "Croatian Kuna", symbol: "kn", code: "HRK" },
    { name: "Cuba", country: "CU", currency: "Cuban Peso", symbol: "$", code: "CUP" },
    { name: "Cyprus", country: "CY", currency: "Euro", symbol: "€", code: "EUR" },
    { name: "Czech Republic", country: "CZ", currency: "Czech Koruna", symbol: "Kč", code: "CZK" },
    { name: "Denmark", country: "DK", currency: "Danish Krone", symbol: "kr", code: "DKK" },
    { name: "Djibouti", country: "DJ", currency: "Djiboutian Franc", symbol: "Fdj", code: "DJF" },
    { name: "Dominica", country: "DM", currency: "East Caribbean Dollar", symbol: "EC$", code: "XCD" },
    { name: "Dominican Republic", country: "DO", currency: "Dominican Peso", symbol: "RD$", code: "DOP" },
    { name: "East Timor (Timor-Leste)", country: "TL", currency: "US Dollar", symbol: "$", code: "USD" },
    { name: "Ecuador", country: "EC", currency: "US Dollar", symbol: "$", code: "USD" },
    { name: "Egypt", country: "EG", currency: "Egyptian Pound", symbol: "E£", code: "EGP" },
    { name: "El Salvador", country: "SV", currency: "US Dollar", symbol: "$", code: "USD" },
    { name: "Equatorial Guinea", country: "GQ", currency: "Central African CFA Franc", symbol: "FCFA", code: "XAF" },
    { name: "Eritrea", country: "ER", currency: "Eritrean Nakfa", symbol: "Nfk", code: "ERN" },
    { name: "Estonia", country: "EE", currency: "Euro", symbol: "€", code: "EUR" },
    { name: "Eswatini (fmr. Swaziland)", country: "SZ", currency: "Swazi Lilangeni", symbol: "E", code: "SZL" },
    { name: "Ethiopia", country: "ET", currency: "Ethiopian Birr", symbol: "Br", code: "ETB" },
    { name: "Fiji", country: "FJ", currency: "Fijian Dollar", symbol: "FJ$", code: "FJD" },
    { name: "Finland", country: "FI", currency: "Euro", symbol: "€", code: "EUR" },
    { name: "France", country: "FR", currency: "Euro", symbol: "€", code: "EUR" },
    { name: "Gabon", country: "GA", currency: "Central African CFA Franc", symbol: "FCFA", code: "XAF" },
    { name: "Gambia", country: "GM", currency: "Gambian Dalasi", symbol: "D", code: "GMD" },
    { name: "Georgia", country: "GE", currency: "Georgian Lari", symbol: "₾", code: "GEL" },
    { name: "Germany", country: "DE", currency: "Euro", symbol: "€", code: "EUR" },
    { name: "Ghana", country: "GH", currency: "Ghanaian Cedi", symbol: "₵", code: "GHS" },
    { name: "Greece", country: "GR", currency: "Euro", symbol: "€", code: "EUR" },
    { name: "Grenada", country: "GD", currency: "East Caribbean Dollar", symbol: "EC$", code: "XCD" },
    { name: "Guatemala", country: "GT", currency: "Guatemalan Quetzal", symbol: "Q", code: "GTQ" },
    { name: "Guinea", country: "GN", currency: "Guinean Franc", symbol: "FG", code: "GNF" },
    { name: "Guinea-Bissau", country: "GW", currency: "West African CFA Franc", symbol: "CFA", code: "XOF" },
    { name: "Guyana", country: "GY", currency: "Guyanese Dollar", symbol: "$", code: "GYD" },
    { name: "Haiti", country: "HT", currency: "Haitian Gourde", symbol: "G", code: "HTG" },
    { name: "Honduras", country: "HN", currency: "Honduran Lempira", symbol: "L", code: "HNL" },
    { name: "Hong Kong", country: "HK", currency: "Hong Kong Dollar", symbol: "HK$", code: "HKD" },
    { name: "Hungary", country: "HU", currency: "Hungarian Forint", symbol: "Ft", code: "HUF" },
    { name: "Iceland", country: "IS", currency: "Icelandic Krona", symbol: "kr", code: "ISK" },
    { name: "India", country: "IN", currency: "Indian Rupee", symbol: "₹", code: "INR" },
    { name: "Indonesia", country: "ID", currency: "Indonesian Rupiah", symbol: "Rp", code: "IDR" },
    { name: "Iran", country: "IR", currency: "Iranian Rial", symbol: "﷼", code: "IRR" },
    { name: "Iraq", country: "IQ", currency: "Iraqi Dinar", symbol: "ع.د", code: "IQD" },
    { name: "Ireland", country: "IE", currency: "Euro", symbol: "€", code: "EUR" },
    { name: "Israel", country: "IL", currency: "Israeli Shekel", symbol: "₪", code: "ILS" },
    { name: "Italy", country: "IT", currency: "Euro", symbol: "€", code: "EUR" },
    { name: "Jamaica", country: "JM", currency: "Jamaican Dollar", symbol: "J$", code: "JMD" },
    { name: "Japan", country: "JP", currency: "Japanese Yen", symbol: "¥", code: "JPY" },
    { name: "Jordan", country: "JO", currency: "Jordanian Dinar", symbol: "JD", code: "JOD" },
    { name: "Kazakhstan", country: "KZ", currency: "Kazakhstani Tenge", symbol: "₸", code: "KZT" },
    { name: "Kenya", country: "KE", currency: "Kenyan Shilling", symbol: "KSh", code: "KES" },
    { name: "Kiribati", country: "KI", currency: "Australian Dollar", symbol: "A$", code: "AUD" },
    { name: "Korea, North", country: "KP", currency: "North Korean Won", symbol: "₩", code: "KPW" },
    { name: "Korea, South", country: "KR", currency: "South Korean Won", symbol: "₩", code: "KRW" },
    { name: "Kosovo", country: "XK", currency: "Euro", symbol: "€", code: "EUR" },
    { name: "Kuwait", country: "KW", currency: "Kuwaiti Dinar", symbol: "د.ك", code: "KWD" },
    { name: "Kyrgyzstan", country: "KG", currency: "Kyrgyzstani Som", symbol: "сом", code: "KGS" },
    { name: "Laos", country: "LA", currency: "Lao Kip", symbol: "₭", code: "LAK" },
    { name: "Latvia", country: "LV", currency: "Euro", symbol: "€", code: "EUR" },
    { name: "Lebanon", country: "LB", currency: "Lebanese Pound", symbol: "ل.ل", code: "LBP" },
    { name: "Lesotho", country: "LS", currency: "Lesotho Loti", symbol: "L", code: "LSL" },
    { name: "Liberia", country: "LR", currency: "Liberian Dollar", symbol: "LD$", code: "LRD" },
    { name: "Libya", country: "LY", currency: "Libyan Dinar", symbol: "ل.د", code: "LYD" },
    { name: "Liechtenstein", country: "LI", currency: "Swiss Franc", symbol: "CHF", code: "CHF" },
    { name: "Lithuania", country: "LT", currency: "Euro", symbol: "€", code: "EUR" },
    { name: "Luxembourg", country: "LU", currency: "Euro", symbol: "€", code: "EUR" },
    { name: "Madagascar", country: "MG", currency: "Malagasy Ariary", symbol: "Ar", code: "MGA" },
    { name: "Malawi", country: "MW", currency: "Malawian Kwacha", symbol: "MK", code: "MWK" },
    { name: "Malaysia", country: "MY", currency: "Malaysian Ringgit", symbol: "RM", code: "MYR" },
    { name: "Maldives", country: "MV", currency: "Maldivian Rufiyaa", symbol: "ރ.", code: "MVR" },
    { name: "Mali", country: "ML", currency: "West African CFA Franc", symbol: "CFA", code: "XOF" },
    { name: "Malta", country: "MT", currency: "Euro", symbol: "€", code: "EUR" },
    { name: "Marshall Islands", country: "MH", currency: "US Dollar", symbol: "$", code: "USD" },
    { name: "Mauritania", country: "MR", currency: "Mauritanian Ouguiya", symbol: "UM", code: "MRU" },
    { name: "Mauritius", country: "MU", currency: "Mauritian Rupee", symbol: "₨", code: "MUR" },
    { name: "Mexico", country: "MX", currency: "Mexican Peso", symbol: "$", code: "MXN" },
    { name: "Micronesia", country: "FM", currency: "US Dollar", symbol: "$", code: "USD" },
    { name: "Moldova", country: "MD", currency: "Moldovan Leu", symbol: "lei", code: "MDL" },
    { name: "Monaco", country: "MC", currency: "Euro", symbol: "€", code: "EUR" },
    { name: "Mongolia", country: "MN", currency: "Mongolian Tugrik", symbol: "₮", code: "MNT" },
    { name: "Montenegro", country: "ME", currency: "Euro", symbol: "€", code: "EUR" },
    { name: "Morocco", country: "MA", currency: "Moroccan Dirham", symbol: "د.م.", code: "MAD" },
    { name: "Mozambique", country: "MZ", currency: "Mozambican Metical", symbol: "MT", code: "MZN" },
    { name: "Myanmar (Burma)", country: "MM", currency: "Myanmar Kyat", symbol: "Ks", code: "MMK" },
    { name: "Namibia", country: "NA", currency: "Namibian Dollar", symbol: "N$", code: "NAD" },
    { name: "Nauru", country: "NR", currency: "Australian Dollar", symbol: "A$", code: "AUD" },
    { name: "Nepal", country: "NP", currency: "Nepalese Rupee", symbol: "₨", code: "NPR" },
    { name: "Netherlands", country: "NL", currency: "Euro", symbol: "€", code: "EUR" },
    { name: "New Zealand", country: "NZ", currency: "New Zealand Dollar", symbol: "NZ$", code: "NZD" },
    { name: "Nicaragua", country: "NI", currency: "Nicaraguan Cordoba", symbol: "C$", code: "NIO" },
    { name: "Niger", country: "NE", currency: "West African CFA Franc", symbol: "CFA", code: "XOF" },
    { name: "Nigeria", country: "NG", currency: "Nigerian Naira", symbol: "₦", code: "NGN" },
    { name: "North Macedonia", country: "MK", currency: "Macedonian Denar", symbol: "ден", code: "MKD" },
    { name: "Norway", country: "NO", currency: "Norwegian Krone", symbol: "kr", code: "NOK" },
    { name: "Oman", country: "OM", currency: "Omani Rial", symbol: "ر.ع.", code: "OMR" },
    { name: "Pakistan", country: "PK", currency: "Pakistani Rupee", symbol: "₨", code: "PKR" },
    { name: "Palau", country: "PW", currency: "US Dollar", symbol: "$", code: "USD" },
    { name: "Panama", country: "PA", currency: "Panamanian Balboa", symbol: "B/.", code: "PAB" },
    { name: "Papua New Guinea", country: "PG", currency: "Papua New Guinean Kina", symbol: "K", code: "PGK" },
    { name: "Paraguay", country: "PY", currency: "Paraguayan Guarani", symbol: "₲", code: "PYG" },
    { name: "Peru", country: "PE", currency: "Peruvian Sol", symbol: "S/.", code: "PEN" },
    { name: "Philippines", country: "PH", currency: "Philippine Peso", symbol: "₱", code: "PHP" },
    { name: "Poland", country: "PL", currency: "Polish Zloty", symbol: "zł", code: "PLN" },
    { name: "Portugal", country: "PT", currency: "Euro", symbol: "€", code: "EUR" },
    { name: "Qatar", country: "QA", currency: "Qatari Riyal", symbol: "ر.ق", code: "QAR" },
    { name: "Romania", country: "RO", currency: "Romanian Leu", symbol: "lei", code: "RON" },
    { name: "Russia", country: "RU", currency: "Russian Ruble", symbol: "₽", code: "RUB" },
    { name: "Rwanda", country: "RW", currency: "Rwandan Franc", symbol: "RF", code: "RWF" },
    { name: "Saint Kitts and Nevis", country: "KN", currency: "East Caribbean Dollar", symbol: "EC$", code: "XCD" },
    { name: "Saint Lucia", country: "LC", currency: "East Caribbean Dollar", symbol: "EC$", code: "XCD" },
    { name: "Saint Vincent and the Grenadines", country: "VC", currency: "East Caribbean Dollar", symbol: "EC$", code: "XCD" },
    { name: "Samoa", country: "WS", currency: "Samoan Tala", symbol: "WS$", code: "WST" },
    { name: "San Marino", country: "SM", currency: "Euro", symbol: "€", code: "EUR" },
    { name: "Sao Tome and Principe", country: "ST", currency: "Dobra", symbol: "Db", code: "STN" },
    { name: "Saudi Arabia", country: "SA", currency: "Saudi Riyal", symbol: "ر.س", code: "SAR" },
    { name: "Senegal", country: "SN", currency: "West African CFA Franc", symbol: "CFA", code: "XOF" },
    { name: "Serbia", country: "RS", currency: "Serbian Dinar", symbol: "дин.", code: "RSD" },
    { name: "Seychelles", country: "SC", currency: "Seychellois Rupee", symbol: "₨", code: "SCR" },
    { name: "Sierra Leone", country: "SL", currency: "Sierra Leonean Leone", symbol: "Le", code: "SLL" },
    { name: "Singapore", country: "SG", currency: "Singapore Dollar", symbol: "S$", code: "SGD" },
    { name: "Slovakia", country: "SK", currency: "Euro", symbol: "€", code: "EUR" },
    { name: "Slovenia", country: "SI", currency: "Euro", symbol: "€", code: "EUR" },
    { name: "Solomon Islands", country: "SB", currency: "Solomon Islands Dollar", symbol: "SI$", code: "SBD" },
    { name: "Somalia", country: "SO", currency: "Somali Shilling", symbol: "S", code: "SOS" },
    { name: "South Africa", country: "ZA", currency: "South African Rand", symbol: "R", code: "ZAR" },
    { name: "South Sudan", country: "SS", currency: "South Sudanese Pound", symbol: "SSP", code: "SSP" },
    { name: "Spain", country: "ES", currency: "Euro", symbol: "€", code: "EUR" },
    { name: "Sri Lanka", country: "LK", currency: "Sri Lankan Rupee", symbol: "₨", code: "LKR" },
    { name: "Sudan", country: "SD", currency: "Sudanese Pound", symbol: "ج.س.", code: "SDG" },
    { name: "Suriname", country: "SR", currency: "Surinamese Dollar", symbol: "$", code: "SRD" },
    { name: "Sweden", country: "SE", currency: "Swedish Krona", symbol: "kr", code: "SEK" },
    { name: "Switzerland", country: "CH", currency: "Swiss Franc", symbol: "CHF", code: "CHF" },
    { name: "Syria", country: "SY", currency: "Syrian Pound", symbol: "£S", code: "SYP" },
    { name: "Taiwan", country: "TW", currency: "New Taiwan Dollar", symbol: "NT$", code: "TWD" },
    { name: "Tajikistan", country: "TJ", currency: "Tajikistani Somoni", symbol: "ЅМ", code: "TJS" },
    { name: "Tanzania", country: "TZ", currency: "Tanzanian Shilling", symbol: "TSh", code: "TZS" },
    { name: "Thailand", country: "TH", currency: "Thai Baht", symbol: "฿", code: "THB" },
    { name: "Togo", country: "TG", currency: "West African CFA Franc", symbol: "CFA", code: "XOF" },
    { name: "Tonga", country: "TO", currency: "Tongan Pa'anga", symbol: "T$", code: "TOP" },
    { name: "Trinidad and Tobago", country: "TT", currency: "Trinidad and Tobago Dollar", symbol: "TT$", code: "TTD" },
    { name: "Tunisia", country: "TN", currency: "Tunisian Dinar", symbol: "د.ت", code: "TND" },
    { name: "Turkey", country: "TR", currency: "Turkish Lira", symbol: "₺", code: "TRY" },
    { name: "Turkmenistan", country: "TM", currency: "Turkmenistani Manat", symbol: "T", code: "TMT" },
    { name: "Tuvalu", country: "TV", currency: "Australian Dollar", symbol: "A$", code: "AUD" },
    { name: "Uganda", country: "UG", currency: "Ugandan Shilling", symbol: "USh", code: "UGX" },
    { name: "Ukraine", country: "UA", currency: "Ukrainian Hryvnia", symbol: "₴", code: "UAH" },
    { name: "United Arab Emirates", country: "AE", currency: "UAE Dirham", symbol: "د.إ", code: "AED" },
    { name: "United Kingdom", country: "GB", currency: "Pound Sterling", symbol: "£", code: "GBP" },
    { name: "United States", country: "US", currency: "US Dollar", symbol: "$", code: "USD" },
    { name: "Uruguay", country: "UY", currency: "Uruguayan Peso", symbol: "$U", code: "UYU" },
    { name: "Uzbekistan", country: "UZ", currency: "Uzbekistani Som", symbol: "сўм", code: "UZS" },
    { name: "Vanuatu", country: "VU", currency: "Vanuatu Vatu", symbol: "VT", code: "VUV" },
    { name: "Vatican City (Holy See)", country: "VA", currency: "Euro", symbol: "€", code: "EUR" },
    { name: "Venezuela", country: "VE", currency: "Venezuelan Bolivar", symbol: "Bs.S.", code: "VES" },
    { name: "Vietnam", country: "VN", currency: "Vietnamese Dong", symbol: "₫", code: "VND" },
    { name: "Yemen", country: "YE", currency: "Yemeni Rial", symbol: "﷼", code: "YER" },
    { name: "Zambia", country: "ZM", currency: "Zambian Kwacha", symbol: "ZK", code: "ZMW" },
    { name: "Zimbabwe", country: "ZW", currency: "Zimbabwean Dollar", symbol: "Z$", code: "ZWL" }
];
