export const currencies = [
    { name: "Afghanistan", country: "AF", currency: "Afghani", symbol: "؋" },
    { name: "Albania", country: "AL", currency: "Albanian Lek", symbol: "Lek" },
    { name: "Algeria", country: "DZ", currency: "Algerian Dinar", symbol: "د.ج" },
    { name: "Andorra", country: "AD", currency: "Euro", symbol: "€" },
    { name: "Angola", country: "AO", currency: "Angolan Kwanza", symbol: "Kz" },
    { name: "Antigua and Barbuda", country: "AG", currency: "East Caribbean Dollar", symbol: "EC$" },
    { name: "Argentina", country: "AR", currency: "Argentine Peso", symbol: "$" },
    { name: "Armenia", country: "AM", currency: "Armenian Dram", symbol: "֏" },
    { name: "Australia", country: "AU", currency: "Australian Dollar", symbol: "A$" },
    { name: "Austria", country: "AT", currency: "Euro", symbol: "€" },
    { name: "Azerbaijan", country: "AZ", currency: "Azerbaijan Manat", symbol: "₼" },
    { name: "Bahamas", country: "BS", currency: "Bahamian Dollar", symbol: "B$" },
    { name: "Bahrain", country: "BH", currency: "Bahraini Dinar", symbol: "BD" },
    { name: "Bangladesh", country: "BD", currency: "Bangladeshi Taka", symbol: "৳" },
    { name: "Barbados", country: "BB", currency: "Barbadian Dollar", symbol: "Bds$" },
    { name: "Belarus", country: "BY", currency: "Belarusian Ruble", symbol: "Br" },
    { name: "Belgium", country: "BE", currency: "Euro", symbol: "€" },
    { name: "Belize", country: "BZ", currency: "Belize Dollar", symbol: "BZ$" },
    { name: "Benin", country: "BJ", currency: "West African CFA Franc", symbol: "CFA" },
    { name: "Bhutan", country: "BT", currency: "Bhutanese Ngultrum", symbol: "Nu." },
    { name: "Bolivia", country: "BO", currency: "Bolivian Boliviano", symbol: "Bs." },
    { name: "Bosnia and Herzegovina", country: "BA", currency: "Convertible Mark", symbol: "KM" },
    { name: "Botswana", country: "BW", currency: "Botswana Pula", symbol: "P" },
    { name: "Brazil", country: "BR", currency: "Brazilian Real", symbol: "R$" },
    { name: "Brunei", country: "BN", currency: "Brunei Dollar", symbol: "B$" },
    { name: "Bulgaria", country: "BG", currency: "Bulgarian Lev", symbol: "лв" },
    { name: "Burkina Faso", country: "BF", currency: "West African CFA Franc", symbol: "CFA" },
    { name: "Burundi", country: "BI", currency: "Burundian Franc", symbol: "FBu" },
    { name: "Cabo Verde", country: "CV", currency: "Cape Verdean Escudo", symbol: "CVE" },
    { name: "Cambodia", country: "KH", currency: "Cambodian Riel", symbol: "៛" },
    { name: "Cameroon", country: "CM", currency: "Central African CFA Franc", symbol: "FCFA" },
    { name: "Canada", country: "CA", currency: "Canadian Dollar", symbol: "CA$" },
    { name: "Central African Republic", country: "CF", currency: "Central African CFA Franc", symbol: "FCFA" },
    { name: "Chad", country: "TD", currency: "Central African CFA Franc", symbol: "FCFA" },
    { name: "Chile", country: "CL", currency: "Chilean Peso", symbol: "$" },
    { name: "China", country: "CN", currency: "Chinese Yuan Renminbi", symbol: "¥" },
    { name: "Colombia", country: "CO", currency: "Colombian Peso", symbol: "$" },
    { name: "Comoros", country: "KM", currency: "Comorian Franc", symbol: "CF" },
    { name: "Congo (Brazzaville)", country: "CG", currency: "Central African CFA Franc", symbol: "FCFA" },
    { name: "Congo (Kinshasa)", country: "CD", currency: "Congolese Franc", symbol: "FC" },
    { name: "Costa Rica", country: "CR", currency: "Costa Rican Colon", symbol: "₡" },
    { name: "Croatia", country: "HR", currency: "Croatian Kuna", symbol: "kn" },
    { name: "Cuba", country: "CU", currency: "Cuban Peso", symbol: "$" },
    { name: "Cyprus", country: "CY", currency: "Euro", symbol: "€" },
    { name: "Czech Republic", country: "CZ", currency: "Czech Koruna", symbol: "Kč" },
    { name: "Denmark", country: "DK", currency: "Danish Krone", symbol: "kr" },
    { name: "Djibouti", country: "DJ", currency: "Djiboutian Franc", symbol: "Fdj" },
    { name: "Dominica", country: "DM", currency: "East Caribbean Dollar", symbol: "EC$" },
    { name: "Dominican Republic", country: "DO", currency: "Dominican Peso", symbol: "RD$" },
    { name: "East Timor (Timor-Leste)", country: "TL", currency: "US Dollar", symbol: "$" },
    { name: "Ecuador", country: "EC", currency: "US Dollar", symbol: "$" },
    { name: "Egypt", country: "EG", currency: "Egyptian Pound", symbol: "E£" },
    { name: "El Salvador", country: "SV", currency: "US Dollar", symbol: "$" },
    { name: "Equatorial Guinea", country: "GQ", currency: "Central African CFA Franc", symbol: "FCFA" },
    { name: "Eritrea", country: "ER", currency: "Eritrean Nakfa", symbol: "Nfk" },
    { name: "Estonia", country: "EE", currency: "Euro", symbol: "€" },
    { name: "Eswatini (fmr. Swaziland)", country: "SZ", currency: "Swazi Lilangeni", symbol: "E" },
    { name: "Ethiopia", country: "ET", currency: "Ethiopian Birr", symbol: "Br" },
    { name: "Fiji", country: "FJ", currency: "Fijian Dollar", symbol: "FJ$" },
    { name: "Finland", country: "FI", currency: "Euro", symbol: "€" },
    { name: "France", country: "FR", currency: "Euro", symbol: "€" },
    { name: "Gabon", country: "GA", currency: "Central African CFA Franc", symbol: "FCFA" },
    { name: "Gambia", country: "GM", currency: "Gambian Dalasi", symbol: "D" },
    { name: "Georgia", country: "GE", currency: "Georgian Lari", symbol: "₾" },
    { name: "Germany", country: "DE", currency: "Euro", symbol: "€" },
    { name: "Ghana", country: "GH", currency: "Ghanaian Cedi", symbol: "₵" },
    { name: "Greece", country: "GR", currency: "Euro", symbol: "€" },
    { name: "Grenada", country: "GD", currency: "East Caribbean Dollar", symbol: "EC$" },
    { name: "Guatemala", country: "GT", currency: "Guatemalan Quetzal", symbol: "Q" },
    { name: "Guinea", country: "GN", currency: "Guinean Franc", symbol: "FG" },
    { name: "Guinea-Bissau", country: "GW", currency: "West African CFA Franc", symbol: "CFA" },
    { name: "Guyana", country: "GY", currency: "Guyanese Dollar", symbol: "$" },
    { name: "Haiti", country: "HT", currency: "Haitian Gourde", symbol: "G" },
    { name: "Honduras", country: "HN", currency: "Honduran Lempira", symbol: "L" },
    { name: "Hong Kong", country: "HK", currency: "Hong Kong Dollar", symbol: "HK$" },
    { name: "Hungary", country: "HU", currency: "Hungarian Forint", symbol: "Ft" },
    { name: "Iceland", country: "IS", currency: "Icelandic Krona", symbol: "kr" },
    { name: "India", country: "IN", currency: "Indian Rupee", symbol: "₹" },
    { name: "Indonesia", country: "ID", currency: "Indonesian Rupiah", symbol: "Rp" },
    { name: "Iran", country: "IR", currency: "Iranian Rial", symbol: "﷼" },
    { name: "Iraq", country: "IQ", currency: "Iraqi Dinar", symbol: "ع.د" },
    { name: "Ireland", country: "IE", currency: "Euro", symbol: "€" },
    { name: "Israel", country: "IL", currency: "Israeli Shekel", symbol: "₪" },
    { name: "Italy", country: "IT", currency: "Euro", symbol: "€" },
    { name: "Jamaica", country: "JM", currency: "Jamaican Dollar", symbol: "J$" },
    { name: "Japan", country: "JP", currency: "Japanese Yen", symbol: "¥" },
    { name: "Jordan", country: "JO", currency: "Jordanian Dinar", symbol: "JD" },
    { name: "Kazakhstan", country: "KZ", currency: "Kazakhstani Tenge", symbol: "₸" },
    { name: "Kenya", country: "KE", currency: "Kenyan Shilling", symbol: "KSh" },
    { name: "Kiribati", country: "KI", currency: "Australian Dollar", symbol: "A$" },
    { name: "Korea, North", country: "KP", currency: "North Korean Won", symbol: "₩" },
    { name: "Korea, South", country: "KR", currency: "South Korean Won", symbol: "₩" },
    { name: "Kosovo", country: "XK", currency: "Euro", symbol: "€" },
    { name: "Kuwait", country: "KW", currency: "Kuwaiti Dinar", symbol: "د.ك" },
    { name: "Kyrgyzstan", country: "KG", currency: "Kyrgyzstani Som", symbol: "сом" },
    { name: "Laos", country: "LA", currency: "Lao Kip", symbol: "₭" },
    { name: "Latvia", country: "LV", currency: "Euro", symbol: "€" },
    { name: "Lebanon", country: "LB", currency: "Lebanese Pound", symbol: "ل.ل" },
    { name: "Lesotho", country: "LS", currency: "Lesotho Loti", symbol: "L" },
    { name: "Liberia", country: "LR", currency: "Liberian Dollar", symbol: "LD$" },
    { name: "Libya", country: "LY", currency: "Libyan Dinar", symbol: "ل.د" },
    { name: "Liechtenstein", country: "LI", currency: "Swiss Franc", symbol: "CHF" },
    { name: "Lithuania", country: "LT", currency: "Euro", symbol: "€" },
    { name: "Luxembourg", country: "LU", currency: "Euro", symbol: "€" },
    { name: "Madagascar", country: "MG", currency: "Malagasy Ariary", symbol: "Ar" },
    { name: "Malawi", country: "MW", currency: "Malawian Kwacha", symbol: "MK" },
    { name: "Malaysia", country: "MY", currency: "Malaysian Ringgit", symbol: "RM" },
    { name: "Maldives", country: "MV", currency: "Maldivian Rufiyaa", symbol: "ރ." },
    { name: "Mali", country: "ML", currency: "West African CFA Franc", symbol: "CFA" },
    { name: "Malta", country: "MT", currency: "Euro", symbol: "€" },
    { name: "Marshall Islands", country: "MH", currency: "US Dollar", symbol: "$" },
    { name: "Mauritania", country: "MR", currency: "Mauritanian Ouguiya", symbol: "UM" },
    { name: "Mauritius", country: "MU", currency: "Mauritian Rupee", symbol: "₨" },
    { name: "Mexico", country: "MX", currency: "Mexican Peso", symbol: "$" },
    { name: "Micronesia", country: "FM", currency: "US Dollar", symbol: "$" },
    { name: "Moldova", country: "MD", currency: "Moldovan Leu", symbol: "lei" },
    { name: "Monaco", country: "MC", currency: "Euro", symbol: "€" },
    { name: "Mongolia", country: "MN", currency: "Mongolian Tugrik", symbol: "₮" },
    { name: "Montenegro", country: "ME", currency: "Euro", symbol: "€" },
    { name: "Morocco", country: "MA", currency: "Moroccan Dirham", symbol: "د.م." },
    { name: "Mozambique", country: "MZ", currency: "Mozambican Metical", symbol: "MT" },
    { name: "Myanmar (Burma)", country: "MM", currency: "Myanmar Kyat", symbol: "Ks" },
    { name: "Namibia", country: "NA", currency: "Namibian Dollar", symbol: "N$" },
    { name: "Nauru", country: "NR", currency: "Australian Dollar", symbol: "A$" },
    { name: "Nepal", country: "NP", currency: "Nepalese Rupee", symbol: "₨" },
    { name: "Netherlands", country: "NL", currency: "Euro", symbol: "€" },
    { name: "New Zealand", country: "NZ", currency: "New Zealand Dollar", symbol: "NZ$" },
    { name: "Nicaragua", country: "NI", currency: "Nicaraguan Cordoba", symbol: "C$" },
    { name: "Niger", country: "NE", currency: "West African CFA Franc", symbol: "CFA" },
    { name: "Nigeria", country: "NG", currency: "Nigerian Naira", symbol: "₦" },
    { name: "North Macedonia", country: "MK", currency: "Macedonian Denar", symbol: "ден" },
    { name: "Norway", country: "NO", currency: "Norwegian Krone", symbol: "kr" },
    { name: "Oman", country: "OM", currency: "Omani Rial", symbol: "ر.ع." },
    { name: "Pakistan", country: "PK", currency: "Pakistani Rupee", symbol: "₨" },
    { name: "Palau", country: "PW", currency: "US Dollar", symbol: "$" },
    { name: "Panama", country: "PA", currency: "Panamanian Balboa", symbol: "B/." },
    { name: "Papua New Guinea", country: "PG", currency: "Papua New Guinean Kina", symbol: "K" },
    { name: "Paraguay", country: "PY", currency: "Paraguayan Guarani", symbol: "₲" },
    { name: "Peru", country: "PE", currency: "Peruvian Sol", symbol: "S/." },
    { name: "Philippines", country: "PH", currency: "Philippine Peso", symbol: "₱" },
    { name: "Poland", country: "PL", currency: "Polish Zloty", symbol: "zł" },
    { name: "Portugal", country: "PT", currency: "Euro", symbol: "€" },
    { name: "Qatar", country: "QA", currency: "Qatari Riyal", symbol: "ر.ق" },
    { name: "Romania", country: "RO", currency: "Romanian Leu", symbol: "lei" },
    { name: "Russia", country: "RU", currency: "Russian Ruble", symbol: "₽" },
    { name: "Rwanda", country: "RW", currency: "Rwandan Franc", symbol: "RF" },
    { name: "Saint Kitts and Nevis", country: "KN", currency: "East Caribbean Dollar", symbol: "EC$" },
    { name: "Saint Lucia", country: "LC", currency: "East Caribbean Dollar", symbol: "EC$" },
    { name: "Saint Vincent and the Grenadines", country: "VC", currency: "East Caribbean Dollar", symbol: "EC$" },
    { name: "Samoa", country: "WS", currency: "Samoan Tala", symbol: "WS$" },
    { name: "San Marino", country: "SM", currency: "Euro", symbol: "€" },
    { name: "Sao Tome and Principe", country: "ST", currency: "Dobra", symbol: "Db" },
    { name: "Saudi Arabia", country: "SA", currency: "Saudi Riyal", symbol: "ر.س" },
    { name: "Senegal", country: "SN", currency: "West African CFA Franc", symbol: "CFA" },
    { name: "Serbia", country: "RS", currency: "Serbian Dinar", symbol: "дин." },
    { name: "Seychelles", country: "SC", currency: "Seychellois Rupee", symbol: "₨" },
    { name: "Sierra Leone", country: "SL", currency: "Sierra Leonean Leone", symbol: "Le" },
    { name: "Singapore", country: "SG", currency: "Singapore Dollar", symbol: "S$" },
    { name: "Slovakia", country: "SK", currency: "Euro", symbol: "€" },
    { name: "Slovenia", country: "SI", currency: "Euro", symbol: "€" },
    { name: "Solomon Islands", country: "SB", currency: "Solomon Islands Dollar", symbol: "SI$" },
    { name: "Somalia", country: "SO", currency: "Somali Shilling", symbol: "S" },
    { name: "South Africa", country: "ZA", currency: "South African Rand", symbol: "R" },
    { name: "South Sudan", country: "SS", currency: "South Sudanese Pound", symbol: "SSP" },
    { name: "Spain", country: "ES", currency: "Euro", symbol: "€" },
    { name: "Sri Lanka", country: "LK", currency: "Sri Lankan Rupee", symbol: "₨" },
    { name: "Sudan", country: "SD", currency: "Sudanese Pound", symbol: "ج.س." },
    { name: "Suriname", country: "SR", currency: "Surinamese Dollar", symbol: "$" },
    { name: "Sweden", country: "SE", currency: "Swedish Krona", symbol: "kr" },
    { name: "Switzerland", country: "CH", currency: "Swiss Franc", symbol: "CHF" },
    { name: "Syria", country: "SY", currency: "Syrian Pound", symbol: "£S" },
    { name: "Taiwan", country: "TW", currency: "New Taiwan Dollar", symbol: "NT$" },
    { name: "Tajikistan", country: "TJ", currency: "Tajikistani Somoni", symbol: "ЅМ" },
    { name: "Tanzania", country: "TZ", currency: "Tanzanian Shilling", symbol: "TSh" },
    { name: "Thailand", country: "TH", currency: "Thai Baht", symbol: "฿" },
    { name: "Togo", country: "TG", currency: "West African CFA Franc", symbol: "CFA" },
    { name: "Tonga", country: "TO", currency: "Tongan Pa'anga", symbol: "T$" },
    { name: "Trinidad and Tobago", country: "TT", currency: "Trinidad and Tobago Dollar", symbol: "TT$" },
    { name: "Tunisia", country: "TN", currency: "Tunisian Dinar", symbol: "د.ت" },
    { name: "Turkey", country: "TR", currency: "Turkish Lira", symbol: "₺" },
    { name: "Turkmenistan", country: "TM", currency: "Turkmenistani Manat", symbol: "T" },
    { name: "Tuvalu", country: "TV", currency: "Australian Dollar", symbol: "A$" },
    { name: "Uganda", country: "UG", currency: "Ugandan Shilling", symbol: "USh" },
    { name: "Ukraine", country: "UA", currency: "Ukrainian Hryvnia", symbol: "₴" },
    { name: "United Arab Emirates", country: "AE", currency: "UAE Dirham", symbol: "د.إ" },
    { name: "United Kingdom", country: "GB", currency: "Pound Sterling", symbol: "£" },
    { name: "United States", country: "US", currency: "US Dollar", symbol: "$" },
    { name: "Uruguay", country: "UY", currency: "Uruguayan Peso", symbol: "$U" },
    { name: "Uzbekistan", country: "UZ", currency: "Uzbekistani Som", symbol: "сўм" },
    { name: "Vanuatu", country: "VU", currency: "Vanuatu Vatu", symbol: "VT" },
    { name: "Vatican City (Holy See)", country: "VA", currency: "Euro", symbol: "€" },
    { name: "Venezuela", country: "VE", currency: "Venezuelan Bolivar", symbol: "Bs.S." },
    { name: "Vietnam", country: "VN", currency: "Vietnamese Dong", symbol: "₫" },
    { name: "Yemen", country: "YE", currency: "Yemeni Rial", symbol: "﷼" },
    { name: "Zambia", country: "ZM", currency: "Zambian Kwacha", symbol: "ZK" },
    { name: "Zimbabwe", country: "ZW", currency: "Zimbabwean Dollar", symbol: "Z$" }
];
